DELETE FROM public.products;
INSERT INTO public.products (id, name, unit, type, category, "categoryId", base_mrp, current_stock) VALUES
(gen_random_uuid(), '10 Fluted Panel 2507', '10 Pcs', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), '19 Regular Gampa Gamela Tasla', 'Standard', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), '3 Inch Putty Knife Soft', '3 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), '3 Inch Singal Brush', '3 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), '3.5 18mm Ultracel Iron Screw', '18mm', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), '3.5x19mm Drywall Screw', '19mm', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), '3.5x25mm Drywall Screw', '25mm', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), '4 Inch Crown Double Brush', '4 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), '4 Inch Putty Knife Soft', '4 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), '40 Gi Ceiling Cross Patti', '8FT', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), '40 Gi Ceiling L Angle', '8FT', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), '40 Gi Ceiling Main Bottom', '8FT', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), '50 Gi Ceiling Main Bottom', '8FT', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), '5050 Sup Painting Brush', '25mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), '555 Delux', '75mm', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), '5in1 Accent Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), '5in1 Amethyst Shower', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), '5in1 Amethyst Shower', '500ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), '5in1 Brown', '500ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), '5in1 Cherry', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), '5in1 Intermediate Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), '5in1 Portuguese Blu', '50ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), '5in1 Smoke Grey', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), '5in1 White', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), '5in1 White', '500ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), '5in1 White Base', '500ML', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), '6 Foam Roller With Handle', '6 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), '6 Inch Putty Knife Hard', '6 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), '686 4 Inch Double Brush', '4 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), '8 Inch Putty Knife Hard', '8 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), '9 Fur Roller Yello Line', '12mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), '9 Inch Mf Brown Line Refill Nut Zinc Handle', '9 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), '9 Inch Paint Tray', '9 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), '9 Inch Tiger Refill+Nut Zinc Handle', '9 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), '9 Inch Yellow Line Refill Ind+Nut Zinc Handle', '9 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'AB Brush', '100mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Acetone Tinter White Col', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Acrylic Putty', '1KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'Anti-Rust PU Enamel Gold', '100ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Aquatech Crack Filler 10mm', '1KG', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'Aquatech Damp Protect Plus', '1L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'Aquatech FIP BC White', '1L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'Aquatech Roof Coat', '20L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'Aquatech Waterblock 2k', '3KG', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'Aquatech Wp B White Base', '20L', 'base', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'Aquatech WRP', '0.5KG', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'Artist Interior Felt Roller', '9 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'B13 1 Inch Single Brush', '1 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'B13 2 Inch Single Brush', '2 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Blk Tinter Black', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Blok Waterstop Damploc Int', '1L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'Blok Waterstop Primecoat Ext Wht', '4L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'Blok Waterstop Primecoat Ext Wht', '10L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'Blok Waterstop Primecoat Ext Wht', '20L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'Blok Waterstop Primecoat Int Wht', '10L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'Blok Waterstop Primecoat Int Wht', '20L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'Blok Waterstop Putty Cem Wht', '40KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'Blok Waterstop Putty Cem Wht Pch', '5KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'Brush', '25mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Brush', '38mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Brush', '50mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Brush', '63mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Brush', '75mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Brush', '100mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Brush', '125mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Capm Silver Calista Aluminum Paints', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Ceiling Channel 20 Nag', '0.3KG', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'CF 13 Style Colour Fresh', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'CF 13 Style Colour Fresh', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Chetak 4 Inch Double Brush', '4 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'CL Blk Colorant Black', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'CL Blu Colorant Blu', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'CL Ext Red Colorant Ext Red', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'CL Ext Yello Colorant Ext Yello', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'CL Grn Colorant Green', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'CL Int Red Colorant Int Red', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'CL Int Yello Colorant Int Yello', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'CL Mag Colorant Megenta', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'CL Ora Colorant Orange', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'CL Rox Colorant Red Oxide', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'CL Swh Colorant Special White', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'CL Vlt Colorant Violet', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'CL Wh Colorant White', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'CL Yox Colorant Yello Oxide', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'CMP R.Oxd Style Covermax RO Primer', '500ML', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'CMP R.Oxd Style Covermax RO Primer', '1L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'CMP R.Oxd Style Covermax RO Primer', '4L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Col Vista DTS MIC Corob TM01', '1EA', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Col Vista Gyro Pad Corob GP01', '1EA', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Col Vista Tints Mac Col BL', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Col Vista Tints Mac Col ER', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Col Vista Tints Mac Col EY', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Col Vista Tints Mac Col HB', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Col Vista Tints Mac Col HG', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Col Vista Tints Mac Col IR', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Col Vista Tints Mac Col IY', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Col Vista Tints Mac Col LB', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Col Vista Tints Mac Col MA', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Col Vista Tints Mac Col MY', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Col Vista Tints Mac Col RO', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Col Vista Tints Mac Col VL', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Col Vista Tints Mac Col WH', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Col Vista Tints Mac Col YO', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Colourdur Gloss Phirozi', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Colourdur Gloss Smoke Grey', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Colourdur Gloss Smoke Grey', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Colourdur PU Enamel Blk', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Colourdur PU Enamel Brl Wht', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Colourdur PU Enamel Brl Wht', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Colourdur PU Enamel Pop Gld Brwn', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Colourdur PU Enamel Pop Gld Brwn', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Colourdur PU Enamel Wild Prpl', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Colourdur PU Enamel Wild Prpl', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Construction Cem White Wash', '1KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'Construction Cem White Wash', '5KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'CSV 99 Calista Clear Synthetic Var', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'DDL Paint Tonic', '500ML', 'direct', 'Other', 'Other', 0, 0),
(gen_random_uuid(), 'DDL Paint Tonic', '1L', 'direct', 'Other', 'Other', 0, 0),
(gen_random_uuid(), 'Decoshield Waterproof Putty', '40KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'Decorative Tape 20mm Golden', '3MT', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Dr Fx Pldproof', '1L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'Dr Fx Pldproof', '5L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'Dulux Floor Plus Paver Grey', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Dulux Floor Plus PO Red', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Dulux Floor Plus Signal Red Plus', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Dulux Floor Plus White', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Dulux Promise Primer', '4L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Dulux Signature Brush Double', '4 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Dulux Smart Brush Double', '5 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Dulux Smatr Brush Double', '4 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Dulux Super Brush Double', '4 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Dulux Superbrush Double', '5 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Duwel Acrylic Distemper', '5KG', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Duwel Acrylic Primer', '4L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Duwel Acrylic Primer', '20L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Duwel Poly Putty', '40KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'Duwel Red Oxide Metal Primer', '1L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Duwel Red Oxide Metal Primer', '20L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Duwel WB Cement Primer', '1L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Duwel WB Cement Primer', '10L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Duwel Wood Primer Pink', '500ML', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Duwel Wood Primer Pink', '1L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Duwel Wood Primer White', '500ML', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Duwel Wood Primer White', '4L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Duwel Wood Primer White', '10L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Economic Paint Roller', '9 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Epoxy', '2L', 'direct', 'Other', 'Other', 0, 0),
(gen_random_uuid(), 'Eterna 92 Base', '3.6L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Fastiner M6 Ultracel', 'Standard', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'FB16 Flat Brush', '16 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Fevicol DDL', '500GM', 'direct', 'Other', 'Other', 0, 0),
(gen_random_uuid(), 'FFR Tinter Fast Fast Red', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Flat Artist', '14 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Flat Artist 8-10-12', 'Standard', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Flat Brush', '8 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Flat Brush', '10 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Flat Brush', '12 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Flat Brush', '14 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Flat Brush', '18 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Floor Coat Paint', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Floor Plus Gun Grey', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Floor Plus Paver Grey', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Floor Plus Po Red', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Floor Plus Signal Red Plus', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Floor Plus White', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Foam Roller', '1-6 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'General Purpose Thinner Pure Mto', '5L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Gi Channel', 'Standard', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Gi Wall Angle', '3000MM', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Gloss Accent Base', '1L', 'base', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Black', '100ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Black', '200ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Black', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Black', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Black', '4L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Br White', '100ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Br White', '4L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Brilliant White', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Dark Brown', '100ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Dark Brown', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Golden Brown', '200ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Golden Brown', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Golden Brown', '20L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Golden Yellow', '100ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Intermediate Base', '500ML', 'base', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Intermediate Base New', '900ML', 'base', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Leaf Brown', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Leaf Brown', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Mahogany', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Middle Buff', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Mim Green', '100ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Off White', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Oxford Blue', '200ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Oxford Blue', '4L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Phiroza', '100ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Phiroza', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Phiroza Blue', '4L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Po Red', '100ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Po Red', '200ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Po Red', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Po Red', '4L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Signal Red', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Smoke Grey', '200ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss Smoke Grey', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss White Base', '500ML', 'base', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss White Base', '1L', 'base', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Gloss White Base New', '4L', 'base', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Green Thread', '9 Inch', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Grg Beading Corner', 'Standard', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Grg Centar Panel', '7 Inch', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Grg Centar Panel', '8 Inch', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Grg Cornice Corner', 'Standard', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Grw Tinter Green', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Gurmala', 'Standard', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Gypsum Board', 'Standard', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Gypsum Plaster Board 1830x1220', '12mm', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Gypsum Plaster Board 6x4', '12mm', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Halo Mist Ext Silk He1', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Halo Mist Ext Silk He2', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Halo Mist Ext Silk He2', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Halo Mist Ext Silk He3', '975ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Halo Mist Ext Silk He3', '9.75L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Halo Mist Ext Silk He4', '950ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Halo Mist Ext Silk He4', '3.8L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Halo Mist Ext Silk He4', '9.5L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Hc Gi Ceiling Inter', '12FT', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Hc Gi Ceiling L Angle', '8FT', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Hc Gi Ceiling Main Bottom', '8FT', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Hc Gi Ceiling Perimeter', '12FT', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Hc Gi Ceiling Section', '12FT', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Hi Performance Enamel Silver', '50ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Hi Performance Enamel Silver', '100ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Hi Performance Enamel Silver', '200ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Hi Performance Enamel Titanium White', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Hi Performance Smoke Gray', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'I Blok Waterstop Damploc Int', '1L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'I Blok Waterstop Primecoat Ext Wht', '10L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'I Blok Waterstop Primecoat Ext Wht', '20L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'I Blok Waterstop Primecoat Int Wht', '10L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'I Blok Waterstop Primecoat Int Wht', '20L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'I Blok Waterstop Putty Cem Wht', '40KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'I Blok Waterstop Putty Cem Wht Pch', '5KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'Ishyn 1k Pu Clr', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Jk Plain Putty', 'Standard', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'Jk Red Oxide Metal Primer', '500ML', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'JN Acrylic Putty', '1KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'JN Acrylic Putty', '20KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'JN Enamel Thinner', '1L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Joie Cls Ext Matt Joe1', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Joie Cls Ext Matt Joe1', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Joie Cls Ext Matt Joe3', '10L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Joie Cls Ext Matt Joe3', '20L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Joie Cls Ext Matt Joe3', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Joie Cls Ext Matt Joey', '10L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Joie Cls Int Matt Bwht', '0.65L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Joie Cls Int Matt Jo1', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Joie Cls Int Matt Jo1', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Joie Cls Int Matt Jo1', '10L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Joie Cls Int Matt Jo1', '20L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Joie Cls Int Matt Jo3', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Joie Cls Int Matt Jo3', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Joie Cls Int Matt Jo3', '20L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'JSW Paints Eco Roller Int Rfek', '9 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'JSW Paints SB Primer Mtl Red Oxide', '1L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'JSW Paints SB Primer Mtl Red Oxide', '5L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'K Shield A Emulsion M.Red', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'K Shield A Emulsion Slp Signal Red', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'K Shield A Emulsion Terracotta', '50ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'K Shield A Emulsion Terracotta', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'K Shield A Emulsion Vibrant Orange', '500ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'K Shield A Emulsion Vibrant Orange', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Kamo Shield Terracotta', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'King Brush', '100mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'KP Red Oxide Metal Primer', '1L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Krayons Wall Putty', '1KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'Krayons Wall Putty', '5KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'Krayons Wall Putty', '40KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'Lamited Gypsum Ceiling Tiles', 'Standard', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'LFY Tinter Light Fast Yellow', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'LWCP', '20KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'Mag Tinter Magenta', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Metallic Accent Gold', '100ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Metallic Accent Gold', '200ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Metallic Accent Gold', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Metallic Paint', '100ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Metallic Paint', '200ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Metallic Paint', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Metallic Paint', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Mineral Oil', '1000ML', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Mineral Oil', '2000ML', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Mineral Oil', '4000ML', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'MRF Melamine Sealer Clear', '8L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Natural Gypsum Calcined Plaster', '20KG', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Natural Gypsum Calcined Plaster', '25KG', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'NC Brown', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'NC Maroon', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'NC Po Red', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'NC Thinner Premium Grade', '1L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Nerolac Brush', '1 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Nerolac Brush', '2 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Nerolac Roller', '4 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Nerolac Roller 452', '4 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Nerolac Roller Ext', '6 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Nerolac Roller Ext', '9 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Nerolac Waterproof Premium Putty', '40KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'NS 97 Calista Neo Star', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'NSS 1 Calista Neo Star Shine', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'NSS 1 Calista Neo Star Shine', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'NSS 1 Calista Neo Star Shine', '10L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'NSS 1 Calista Neo Star Shine', '20L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'NSS 2 Calista Neo Star Shine', '975ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'NSS 2 Calista Neo Star Shine', '9.75L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'NSS 2 Calista Neo Star Shine', '19.5L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'NSS 2 Calista Neo Star Shine', '39L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'NSS 99 Calista Neo Star Shine', '975ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'NSS 99 Calista Neo Star Shine', '3.5L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'NSS 99 Calista Neo Star Shine', '9.75L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Oxri Tinter Red Oxide', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Painting Brush', '38mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Painting Brush', '50mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Painting Brush', '63mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Painting Brush', '75mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Painting Tray', 'Standard', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Paint Brush 001 Sup', '25mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Paint Brush 511tsup', '100mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Paint Brush Ab Sup', '100mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Paint Brush B-5 Sup', '100mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Paint Brush Miton King', '100mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Paint Remover', '1L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'PB 2 Style Power Bright', '975ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'PB 2 Style Power Bright', '3.9L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'PB 2 Style Power Bright', '9.75L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'PB1 Style Power Bright', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'PB1 Style Power Bright', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'PB1 Style Power Bright', '10L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'PB1 Style Power Bright', '20L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'PB White Style Power Bright', '20L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'PCP WH Calista Perfect Choice Primer', '10L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'PCP WH Calista Perfect Choice Primer', '20L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'PF 13 Style Power Fit', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'PF 13 Style Power Fit', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'PF 13 Style Power Fit', '20L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'PF 96 Style Power Fit', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'PF 96 Style Power Fit', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'PFP WH Style Pro Fresh Primer', '1L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'PFP WH Style Pro Fresh Primer', '4L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'PFP WH Style Pro Fresh Primer', '10L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'PFP WH Style Pro Fresh Primer', '20L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'PHP White Style Pro Hide Primer', '1L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'PHP White Style Pro Hide Primer', '4L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'PHP White Style Pro Hide Primer', '10L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'PHP White Style Pro Hide Primer', '20L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Matt PE1', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Matt PE1', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Matt PE1', '10L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Matt PE1', '20L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Matt PE2', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Matt PE2', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Matt PE2', '10L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Matt PE2', '20L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Matt PE3', '975ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Matt PE3', '9.75L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Matt PE3', '19.5L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Matt PE4', '950ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Matt PE4', '3.8L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Matt PE4', '9.5L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Matt PE4', '19L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Matt PEY', '975ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Matt PEY', '3.8L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Matt PEY', '9.75L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Silk PSE1', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Silk PSE1', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Silk PSE1', '10L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Silk PSE1', '20L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Silk PSE2', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Silk PSE2', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Silk PSE2', '10L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Silk PSE2', '20L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Silk PSE3', '975ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Silk PSE3', '9.75L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Silk PSE3', '19.5L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Silk PSE4', '9.5L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Ext Silk PSE4', '19L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Matt PI1', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Matt PI1', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Matt PI1', '10L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Matt PI1', '20L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Matt PI3', '975ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Matt PI3', '3.9L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Matt PI3', '9.75L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Matt PI3', '19.5L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Matt PI4', '950ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Matt PI4', '3.8L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Matt PI4', '9.5L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Matt PI4', '19L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Silk PSI1', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Silk PSI1', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Silk PSI1', '10L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Silk PSI3', '975ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Silk PSI3', '3.9L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Silk PSI3', '9.75L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Silk PSI3', '19.5L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Silk PSI4', '950ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Pixa Elg Int Silk PSI4', '3.8L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Plain Putty', '40KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'PPP White One Pro Primer And Putty', '10KG', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'PPP White One Pro Primer And Putty', '20KG', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Promise 2 IN1 Primer Int Ext', '10L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Promise 2 IN1 Primer Int Ext', '20L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Promise Accent Base', '3.6L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise BR White', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Enml Black', '20L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Promise Exterior 92 Base', '20L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Exterior 94 Base', '4L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Exterior 98 Base', '4L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Exterior Br White Base', '20L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Exterior White Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Exterior White Base', '4L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Exterior White Base', '20L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Interior 92 Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Interior 92 Base', '10L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Interior 92 Base', '20L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Interior 94 Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Interior 96 Base', '4L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Interior ST Base', '4L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Interior Accent Base', '3.6L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Interior Intermediate Base', '900ML', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Interior Intermediate Base', '3.6L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Interior Red Base', '900ML', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Interior White Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Interior White Base', '4L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Interior White Base', '10L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Interior White Base', '20L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Interior Yellow Base', '900ML', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Intermediate Base', '3.6L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Primer', '1L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Promise Primer', '10L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Promise Primer', '20L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Promise Sheen Exterior 94 Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Sheen Exterior 94 Base', '4L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Sheen Exterior Br White', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Sheen Exterior White Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Sheen Exterior White Base', '4L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Sheen Exterior White Base', '10L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Sheen Interior 92 Base', '10L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Sheen Interior 94 Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Sheen Interior Metal Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Sheen Interior White Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Sheen Interior White Base', '4L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Sheen Interior White Base', '10L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Sheen Interior White Base', '20L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Smart C. Acrylic Distemper', '20KG', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Smart Ch Ext Br White Base', '4L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Smart Ch Ext Br White Base', '20L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Smart Ch Ext Primer', '4L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Promise Smart Ch Ext Primer', '10L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Promise Smart Ch Ext Primer', '20L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Promise Smart Ch Int Br White Base', '4L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Smart Ch Int Br White Base', '10L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Smart Ch Int Br White Base', '20L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Smart Ch Int Primer', '1L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Promise Smart Ch Int Primer', '4L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Promise Smart Ch Int Primer', '10L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Promise Smart Ch Int Primer', '20L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Promise Smart Choice Ext Primer', '10L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Promise Smart Choice Int Primer', '10L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Promise Smart Choice Int Primer', '20L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Promise Smart Int Br White Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise White Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Promise Yellow Base', '900ML', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'PSP WH Calista Perfect Choice Primer', '20L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'PSP White Style Perfect Start Primer', '1L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'PSP White Style Perfect Start Primer', '4L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'PSP White Style Perfect Start Primer', '10L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'PU Clear Sealer', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'PU Enamel Black', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'PU Enamel Dark Brown', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'PU Enamel Silver Pant', '50ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'PU Enamel Silver Pant', '100ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'PU Enamel Smoke Grey', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'PU Enamel White', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'PU Semi Gloss', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Putty Blade 3', '3 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Putty Blade 4', '4 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Putty Blade 6', '6 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Putty Blade Hard 6', '6 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Putty Blade Hard 8', '8 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Putty Fine', '40KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'Putty Ftl Cem Sindl Wd Tkn Frag', '20KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'Putty Ftl Cem Sindl Wd Tkn Frag', '40KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'PVC Sleeve', 'Standard', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Rangoli Brush 5', 'Standard', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Red Oxide Metal Primer', '500ML', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Red Oxide Primer Solvent Thinnable', '200ML', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Red Oxide Primer Solvent Thinnable', '500ML', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Red Stone Sup Painting Brush', '100mm', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Roller 46', 'Standard', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Roller Brush', 'Standard', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Roller Brush 6', '6 Inch', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'ROM Primer', '500ML', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'ROM Primer', '1L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'ROM Primer', '4L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Rovere Lite', '20L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Sadolin 2k PU Thinner', '1L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Sadolin Ce 1k PU Gloss', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Sadolin Int Clr 1k PU Gloss', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Sadolin Int Clr 1k PU Gloss', '4L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Sadolin Int Clr 2k PU Gloss', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Sadolin Int Clr Melamine Gloss', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Sadolin Interior 2k PU Sealer', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Sadolin Melamine Thinner', '1L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Sadolin NC Clear Lacquer', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Sadolin NC Sanding Sealer', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Sadolin NC Sanding Sealer', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Sadolin NC Wood Thinner', '1L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Sadolin NC Wood Thinner', '4L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Sadolin Wood Filler White', '1KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'Sat Fin Accent Base', '900ML', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Sat Fin Accent Base', '0.9L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Sat Fin White', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Sat Fin White Base New', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Satin Accent Base', '3.6L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'SB Cement Primer', '1L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Screw 19mm', '19mm', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Screw 25mm', '25mm', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'SGE Ad Grey Calista Sparkle Gloss', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Black Calista Sparkle Gloss', '100ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Black Calista Sparkle Gloss', '200ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Black Calista Sparkle Gloss', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Black Calista Sparkle Gloss', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Black Calista Sparkle Gloss', '4L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Brown Calista Sparkle Gloss', '100ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Brown Calista Sparkle Gloss', '200ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Brown Calista Sparkle Gloss', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Brown Calista Sparkle Gloss', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Brown Calista Sparkle Gloss', '4L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Br White Calista Sparkle Gloss', '200ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Br White Calista Sparkle Gloss', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Br White Calista Sparkle Gloss', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Br White Calista Sparkle Gloss', '4L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Gl Brown Calista Sparkle Gloss', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Gl Brown Calista Sparkle Gloss', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Gl Brown Calista Sparkle Gloss', '4L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Gold Calista Sparkle Gloss', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE S Grey Calista Sparkle Gloss', '20L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Sky Blue Calista Sparkle Gloss', '4L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Wl Lilac Calista Sparkle Gloss', '500ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SGE Wl Lilac Calista Sparkle Gloss', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Shiro Thinner Pl', '20L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Shino Thinner PTL', '5L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Sirca NC Dark Brown', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Sirca NC Golden Yellow', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Sirca NC White', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SNT 22 Allwood Excel One Thinner', '1L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'SNT 22 Allwood Excel One Thinner', '5L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Special 2.5', 'Standard', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Special 5.3', 'Standard', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Special', '10-1-15-15', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'SPNT 22 Allwood Excel 1 Smith Thinner', '1L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'SPNT 22 Allwood Excel 1 Smith Thinner', '5L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Spray Paint Silver', '400ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SRP ROXD Calista Sparkle RO Primer', '1L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'SRP ROXD Calista Sparkle RO Primer', '4L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'SR Spray Paint Black', '400ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SR Spray Paint Deep Orange', '400ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SR Spray Paint Gold', '400ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'SR Spray Paint Silver', '400ML', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'Stainer Black', '200ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Stainer Diluted Pack', '100ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Stainer Fast Blue', '50ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Stainer Fast Yellow Green', '50ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Stainer Fast Yellow Green', '100ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Stainer Fast Yellow Green', '200ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Stainer Yellow Oxide', '100ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Stencil Fairy', 'Standard', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Stencil Green Key', 'Standard', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Stencil 16-24', 'Standard', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Style Stainer Black', '200ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Style Stainer Fast Red', '200ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Style Stainer Fast Violet', '50ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Style Stainer Fast Violet', '100ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Style Stainer Fast Violet', '200ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Style Stainer Fast Yello Green', '20ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Superclean Accent Base', '10L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Superclean Intermediate Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Super Clean New 90 Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Super Clean New 90 Base', '4L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Super Clean New 90 Base', '10L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Super Clean New 90 Base', '20L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Super Clean New 92 Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Super Clean Yellow 96 Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'SWP Pink Calista Sparkle Wood Primer', '1L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'SWP Pink Calista Sparkle Wood Primer', '4L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'SWP Wht Calista Sparkle Wood Primer', '1L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'SWP Wht Calista Sparkle Wood Primer', '4L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Terminator Wood', '250ML', 'direct', 'Other', 'Other', 0, 0),
(gen_random_uuid(), 'Thinner GP Super', '200ML', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Thinner GP Super', '400ML', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Thinner GP Super', '4L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Thinner GP Super', '5L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Thinner GP Super', '900ML', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Thinner J-9', '400ML', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Thinner J-9', '600ML', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Thinner J-9', '700ML', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Thinner J-9', '800ML', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Thinner J-9', '900ML', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Thinner PTL', '1L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Thinner Super GP CG', '18L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Thinner Super GP CG', '21L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'Thinnner Super GP CG', '210L', 'direct', 'Thinner', 'Thinner', 0, 0),
(gen_random_uuid(), 'TLI 1 One True Life', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'TLI 1 One True Life', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'TLI 1 One True Life', '20L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'TLI 2 One True Life', '975ML', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'TLI 2 One True Life', '9.75L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'TLI 2 One True Life', '19.5L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'TLI 2 One True Life', '39L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Tray 225', 'Standard', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'UL Gi Ceiling Inter', '12FT', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'UL Gi Ceiling L Angel', '8FT', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'UL Gi Ceiling L Angel', '12FT', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'UL Gi Ceiling Main Bottom', '8FT', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'UL Gi Ceiling Perimeter', '12FT', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'UL Gi Ceiling Section', '12FT', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Ultra Nitro Sealer', '1L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Ultra Nitro Sealer', '4L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Ultracel Ceiling Drywall Tape', 'Standard', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Ultracel Wire Mesh Roll', 'Standard', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Universal Stainer Black', '50ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Black', '100ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Black', '200ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Fast Blue', '50ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Fast Blue', '100ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Fast Blue', '200ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Fast Green', '50ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Fast Green', '100ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Fast Green', '200ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Fast Orange', '50ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Fast Orange', '100ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Fast Orange', '200ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Fast Red', '200ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Fast Red', '500ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Fast Violet', '50ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Fast Violet', '100ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Fast Violet', '200ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Fast Yellow', '50ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Fast Yellow', '100ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Fast Yellow', '200ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Yellow Oxide', '50ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Universal Stainer Yellow Oxide', '200ML', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'VAF Metallic Silver', '1L', 'direct', 'Enamel', 'Enamel', 0, 0),
(gen_random_uuid(), 'VT Diamond 90 Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'VT Diamond 90 Base', '4L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'VT Diamond 90 Base', '10L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'VT Diamond 90 Base', '11L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'VT Diamond 90 Base', '20L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'VT Diamond 92 Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'VT Diamond 92 Base', '20L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'VT Diamond White Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'VT Diamond White Base', '4L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'VT Eterna 90 Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'VT Eterna 90 Base', '20L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'VT Pearl Glo Accent Base', '900ML', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'VT Pearl Glo New White Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'VT Pearl Glo New White Base', '10L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Wall Paints Stencils', 'Standard', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Wall Prim Joie Ext Wht', '10L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Wall Prim Joie Ext Wht', '20L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Wall Prim Joie Int Wht', '10L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Wall Prim Joie Int Wht', '20L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Wall Putty Acrylic Wht', '5KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'Wall Putty Cem Sndl Wd Fragrance', '40KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'Wallstencil Srl Painting Tool', 'Standard', 'direct', 'Tools/Brushes', 'Tools/Brushes', 0, 0),
(gen_random_uuid(), 'Washer', 'Standard', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Waterproof Putty', '20KG', 'direct', 'Putty', 'Putty', 0, 0),
(gen_random_uuid(), 'WF4 White Alldry Wallfix 4', '4L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'WF4 White Alldry Wallfix 4', '10L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'WF4 White Alldry Wallfix 4', '20L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'White Gi Short Cross T', '600MM', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'White Primer Solvent Thinnable', '500ML', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'WS 201 ABP', 'Standard', 'direct', 'Other', 'Other', 0, 0),
(gen_random_uuid(), 'WS Alkali Bloc Primer', '4L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'WS Flash Accent Base', '900ML', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Flash Accent Base', '3.6L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Flash Intermediate Base', '3.6L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Max 10YR 90 Base', '4L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Max 10YR 90 Base', '10L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Max 10YR 90 Base', '20L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Max 10YR 92 Base', '10L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Max 10YR 92 Base', '18L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Max 10YR 93 Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Max Accent Base', '3.8L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Max Deep Base', '900ML', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Max White Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS PF 15YR 90 Base', '10L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS PF 15YR 90 Base', '20L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS PF 15YR 92 Base', '4L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS PF 15YR 92 Base', '18L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS PF 15YR 93 Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS PF 92 Base', '18L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS PF BR White', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS PF Deep Base', '900ML', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Power Flex 92 Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Power Flex White Base', '4L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Powerflexx 93 Base', '3.7L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Br White', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Deep Base', '900ML', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Deep Base', '18L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Dust Hi Sheen 90', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Dust Hi Sheen 90', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Dust Hi Sheen 90', '10L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Dust Hi Sheen 90', '20L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Dust Hi Sheen 90 Base', '4L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Dust Hi Sheen 92', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Dust Hi Sheen 93', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Dustproof 90 Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Dustproof 90 Base', '10L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Dustproof 92 Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Dustproof 98 Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Electric Blue', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Electric Blue', '4L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Rainproof Accent Base', '900ML', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Rainproof White Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Red Base', '900ML', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Red Base', '3.6L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Signal Red', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Sunrise', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Teracotta', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Vibrant Yellow Base', '900ML', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect White Base', '1L', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Protect Yellow Base', '900ML', 'base', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Teak 295', 'Standard', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Walnut', 'Standard', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Walnut 307', 'Standard', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Walnut 323', 'Standard', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WS Walnut 353', 'Standard', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'WTP Aquatech Roof Coat', '20L', 'direct', 'Waterproofing', 'Waterproofing', 0, 0),
(gen_random_uuid(), 'Xtra Touch Terracota', '1L', 'direct', 'Emulsion', 'Emulsion', 0, 0),
(gen_random_uuid(), 'Yox Tinter Yellow Oxide', '1L', 'direct', 'Tinter/Colorant', 'Tinter/Colorant', 0, 0),
(gen_random_uuid(), 'Zet Super', '25mm', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Zet Super', '75mm', 'direct', 'Hardware', 'Hardware', 0, 0),
(gen_random_uuid(), 'Zinc Yellow Metal Primer', '1L', 'direct', 'Primer', 'Primer', 0, 0),
(gen_random_uuid(), 'Zinc Yellow Metal Primer', '4L', 'direct', 'Primer', 'Primer', 0, 0);