DELETE FROM public.products;
INSERT INTO public.products (name, unit, type, category, base_mrp, current_stock) VALUES
('10 Fluted Panel 2507', '10 Pcs', 'direct', 'Hardware', 0, 0),
('19 Regular Gampa Gamela Tasla', 'Standard', 'direct', 'Hardware', 0, 0),
('3 Inch Putty Knife Soft', '3 Inch', 'direct', 'Tools/Brushes', 0, 0),
('3 Inch Singal Brush', '3 Inch', 'direct', 'Tools/Brushes', 0, 0),
('3.5 18mm Ultracel Iron Screw', '18mm', 'direct', 'Hardware', 0, 0),
('3.5x19mm Drywall Screw', '19mm', 'direct', 'Hardware', 0, 0),
('3.5x25mm Drywall Screw', '25mm', 'direct', 'Hardware', 0, 0),
('4 Inch Crown Double Brush', '4 Inch', 'direct', 'Tools/Brushes', 0, 0),
('4 Inch Putty Knife Soft', '4 Inch', 'direct', 'Tools/Brushes', 0, 0),
('40 Gi Ceiling Cross Patti', '8FT', 'direct', 'Hardware', 0, 0),
('40 Gi Ceiling L Angle', '8FT', 'direct', 'Hardware', 0, 0),
('40 Gi Ceiling Main Bottom', '8FT', 'direct', 'Hardware', 0, 0),
('50 Gi Ceiling Main Bottom', '8FT', 'direct', 'Hardware', 0, 0),
('5050 Sup Painting Brush', '25mm', 'direct', 'Tools/Brushes', 0, 0),
('555 Delux', '75mm', 'direct', 'Hardware', 0, 0),
('5in1 Accent Base', '1L', 'base', 'Emulsion', 0, 0),
('5in1 Amethyst Shower', '1L', 'direct', 'Emulsion', 0, 0),
('5in1 Amethyst Shower', '500ML', 'direct', 'Emulsion', 0, 0),
('5in1 Brown', '500ML', 'direct', 'Emulsion', 0, 0),
('5in1 Cherry', '1L', 'direct', 'Emulsion', 0, 0),
('5in1 Intermediate Base', '1L', 'base', 'Emulsion', 0, 0),
('5in1 Portuguese Blu', '50ML', 'direct', 'Emulsion', 0, 0),
('5in1 Smoke Grey', '1L', 'direct', 'Emulsion', 0, 0),
('5in1 White', '1L', 'direct', 'Emulsion', 0, 0),
('5in1 White', '500ML', 'direct', 'Emulsion', 0, 0),
('5in1 White Base', '500ML', 'base', 'Emulsion', 0, 0),
('6 Foam Roller With Handle', '6 Inch', 'direct', 'Tools/Brushes', 0, 0),
('6 Inch Putty Knife Hard', '6 Inch', 'direct', 'Tools/Brushes', 0, 0),
('686 4 Inch Double Brush', '4 Inch', 'direct', 'Tools/Brushes', 0, 0),
('8 Inch Putty Knife Hard', '8 Inch', 'direct', 'Tools/Brushes', 0, 0),
('9 Fur Roller Yello Line', '12mm', 'direct', 'Tools/Brushes', 0, 0),
('9 Inch Mf Brown Line Refill Nut Zinc Handle', '9 Inch', 'direct', 'Tools/Brushes', 0, 0),
('9 Inch Paint Tray', '9 Inch', 'direct', 'Tools/Brushes', 0, 0),
('9 Inch Tiger Refill+Nut Zinc Handle', '9 Inch', 'direct', 'Tools/Brushes', 0, 0),
('9 Inch Yellow Line Refill Ind+Nut Zinc Handle', '9 Inch', 'direct', 'Tools/Brushes', 0, 0),
('AB Brush', '100mm', 'direct', 'Tools/Brushes', 0, 0),
('Acetone Tinter White Col', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Acrylic Putty', '1KG', 'direct', 'Putty', 0, 0),
('Anti-Rust PU Enamel Gold', '100ML', 'direct', 'Enamel', 0, 0),
('Aquatech Crack Filler 10mm', '1KG', 'direct', 'Waterproofing', 0, 0),
('Aquatech Damp Protect Plus', '1L', 'direct', 'Waterproofing', 0, 0),
('Aquatech FIP BC White', '1L', 'direct', 'Waterproofing', 0, 0),
('Aquatech Roof Coat', '20L', 'direct', 'Waterproofing', 0, 0),
('Aquatech Waterblock 2k', '3KG', 'direct', 'Waterproofing', 0, 0),
('Aquatech Wp B White Base', '20L', 'base', 'Waterproofing', 0, 0),
('Aquatech WRP', '0.5KG', 'direct', 'Waterproofing', 0, 0),
('Artist Interior Felt Roller', '9 Inch', 'direct', 'Tools/Brushes', 0, 0),
('B13 1 Inch Single Brush', '1 Inch', 'direct', 'Tools/Brushes', 0, 0),
('B13 2 Inch Single Brush', '2 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Blk Tinter Black', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Blok Waterstop Damploc Int', '1L', 'direct', 'Waterproofing', 0, 0),
('Blok Waterstop Primecoat Ext Wht', '4L', 'direct', 'Waterproofing', 0, 0),
('Blok Waterstop Primecoat Ext Wht', '10L', 'direct', 'Waterproofing', 0, 0),
('Blok Waterstop Primecoat Ext Wht', '20L', 'direct', 'Waterproofing', 0, 0),
('Blok Waterstop Primecoat Int Wht', '10L', 'direct', 'Waterproofing', 0, 0),
('Blok Waterstop Primecoat Int Wht', '20L', 'direct', 'Waterproofing', 0, 0),
('Blok Waterstop Putty Cem Wht', '40KG', 'direct', 'Putty', 0, 0),
('Blok Waterstop Putty Cem Wht Pch', '5KG', 'direct', 'Putty', 0, 0),
('Brush', '25mm', 'direct', 'Tools/Brushes', 0, 0),
('Brush', '38mm', 'direct', 'Tools/Brushes', 0, 0),
('Brush', '50mm', 'direct', 'Tools/Brushes', 0, 0),
('Brush', '63mm', 'direct', 'Tools/Brushes', 0, 0),
('Brush', '75mm', 'direct', 'Tools/Brushes', 0, 0),
('Brush', '100mm', 'direct', 'Tools/Brushes', 0, 0),
('Brush', '125mm', 'direct', 'Tools/Brushes', 0, 0),
('Capm Silver Calista Aluminum Paints', '1L', 'direct', 'Enamel', 0, 0),
('Ceiling Channel 20 Nag', '0.3KG', 'direct', 'Hardware', 0, 0),
('CF 13 Style Colour Fresh', '1L', 'direct', 'Emulsion', 0, 0),
('CF 13 Style Colour Fresh', '4L', 'direct', 'Emulsion', 0, 0),
('Chetak 4 Inch Double Brush', '4 Inch', 'direct', 'Tools/Brushes', 0, 0),
('CL Blk Colorant Black', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('CL Blu Colorant Blu', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('CL Ext Red Colorant Ext Red', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('CL Ext Yello Colorant Ext Yello', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('CL Grn Colorant Green', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('CL Int Red Colorant Int Red', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('CL Int Yello Colorant Int Yello', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('CL Mag Colorant Megenta', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('CL Ora Colorant Orange', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('CL Rox Colorant Red Oxide', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('CL Swh Colorant Special White', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('CL Vlt Colorant Violet', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('CL Wh Colorant White', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('CL Yox Colorant Yello Oxide', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('CMP R.Oxd Style Covermax RO Primer', '500ML', 'direct', 'Primer', 0, 0),
('CMP R.Oxd Style Covermax RO Primer', '1L', 'direct', 'Primer', 0, 0),
('CMP R.Oxd Style Covermax RO Primer', '4L', 'direct', 'Primer', 0, 0),
('Col Vista DTS MIC Corob TM01', '1EA', 'direct', 'Hardware', 0, 0),
('Col Vista Gyro Pad Corob GP01', '1EA', 'direct', 'Hardware', 0, 0),
('Col Vista Tints Mac Col BL', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Col Vista Tints Mac Col ER', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Col Vista Tints Mac Col EY', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Col Vista Tints Mac Col HB', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Col Vista Tints Mac Col HG', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Col Vista Tints Mac Col IR', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Col Vista Tints Mac Col IY', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Col Vista Tints Mac Col LB', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Col Vista Tints Mac Col MA', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Col Vista Tints Mac Col MY', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Col Vista Tints Mac Col RO', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Col Vista Tints Mac Col VL', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Col Vista Tints Mac Col WH', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Col Vista Tints Mac Col YO', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Colourdur Gloss Phirozi', '1L', 'direct', 'Enamel', 0, 0),
('Colourdur Gloss Smoke Grey', '500ML', 'direct', 'Enamel', 0, 0),
('Colourdur Gloss Smoke Grey', '1L', 'direct', 'Enamel', 0, 0),
('Colourdur PU Enamel Blk', '500ML', 'direct', 'Enamel', 0, 0),
('Colourdur PU Enamel Brl Wht', '500ML', 'direct', 'Enamel', 0, 0),
('Colourdur PU Enamel Brl Wht', '1L', 'direct', 'Enamel', 0, 0),
('Colourdur PU Enamel Pop Gld Brwn', '500ML', 'direct', 'Enamel', 0, 0),
('Colourdur PU Enamel Pop Gld Brwn', '1L', 'direct', 'Enamel', 0, 0),
('Colourdur PU Enamel Wild Prpl', '500ML', 'direct', 'Enamel', 0, 0),
('Colourdur PU Enamel Wild Prpl', '1L', 'direct', 'Enamel', 0, 0),
('Construction Cem White Wash', '1KG', 'direct', 'Putty', 0, 0),
('Construction Cem White Wash', '5KG', 'direct', 'Putty', 0, 0),
('CSV 99 Calista Clear Synthetic Var', '1L', 'direct', 'Enamel', 0, 0),
('DDL Paint Tonic', '500ML', 'direct', 'Other', 0, 0),
('DDL Paint Tonic', '1L', 'direct', 'Other', 0, 0),
('Decoshield Waterproof Putty', '40KG', 'direct', 'Putty', 0, 0),
('Decorative Tape 20mm Golden', '3MT', 'direct', 'Hardware', 0, 0),
('Dr Fx Pldproof', '1L', 'direct', 'Waterproofing', 0, 0),
('Dr Fx Pldproof', '5L', 'direct', 'Waterproofing', 0, 0),
('Dulux Floor Plus Paver Grey', '1L', 'direct', 'Enamel', 0, 0),
('Dulux Floor Plus PO Red', '1L', 'direct', 'Enamel', 0, 0),
('Dulux Floor Plus Signal Red Plus', '1L', 'direct', 'Enamel', 0, 0),
('Dulux Floor Plus White', '1L', 'direct', 'Enamel', 0, 0),
('Dulux Promise Primer', '4L', 'direct', 'Primer', 0, 0),
('Dulux Signature Brush Double', '4 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Dulux Smart Brush Double', '5 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Dulux Smatr Brush Double', '4 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Dulux Super Brush Double', '4 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Dulux Superbrush Double', '5 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Duwel Acrylic Distemper', '5KG', 'direct', 'Emulsion', 0, 0),
('Duwel Acrylic Primer', '4L', 'direct', 'Primer', 0, 0),
('Duwel Acrylic Primer', '20L', 'direct', 'Primer', 0, 0),
('Duwel Poly Putty', '40KG', 'direct', 'Putty', 0, 0),
('Duwel Red Oxide Metal Primer', '1L', 'direct', 'Primer', 0, 0),
('Duwel Red Oxide Metal Primer', '20L', 'direct', 'Primer', 0, 0),
('Duwel WB Cement Primer', '1L', 'direct', 'Primer', 0, 0),
('Duwel WB Cement Primer', '10L', 'direct', 'Primer', 0, 0),
('Duwel Wood Primer Pink', '500ML', 'direct', 'Primer', 0, 0),
('Duwel Wood Primer Pink', '1L', 'direct', 'Primer', 0, 0),
('Duwel Wood Primer White', '500ML', 'direct', 'Primer', 0, 0),
('Duwel Wood Primer White', '4L', 'direct', 'Primer', 0, 0),
('Duwel Wood Primer White', '10L', 'direct', 'Primer', 0, 0),
('Economic Paint Roller', '9 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Epoxy', '2L', 'direct', 'Other', 0, 0),
('Eterna 92 Base', '3.6L', 'base', 'Emulsion', 0, 0),
('Fastiner M6 Ultracel', 'Standard', 'direct', 'Hardware', 0, 0),
('FB16 Flat Brush', '16 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Fevicol DDL', '500GM', 'direct', 'Other', 0, 0),
('FFR Tinter Fast Fast Red', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Flat Artist', '14 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Flat Artist 8-10-12', 'Standard', 'direct', 'Tools/Brushes', 0, 0),
('Flat Brush', '8 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Flat Brush', '10 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Flat Brush', '12 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Flat Brush', '14 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Flat Brush', '18 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Floor Coat Paint', '500ML', 'direct', 'Enamel', 0, 0),
('Floor Plus Gun Grey', '1L', 'direct', 'Enamel', 0, 0),
('Floor Plus Paver Grey', '1L', 'direct', 'Enamel', 0, 0),
('Floor Plus Po Red', '1L', 'direct', 'Enamel', 0, 0),
('Floor Plus Signal Red Plus', '1L', 'direct', 'Enamel', 0, 0),
('Floor Plus White', '1L', 'direct', 'Enamel', 0, 0),
('Foam Roller', '1-6 Inch', 'direct', 'Tools/Brushes', 0, 0),
('General Purpose Thinner Pure Mto', '5L', 'direct', 'Thinner', 0, 0),
('Gi Channel', 'Standard', 'direct', 'Hardware', 0, 0),
('Gi Wall Angle', '3000MM', 'direct', 'Hardware', 0, 0),
('Gloss Accent Base', '1L', 'base', 'Enamel', 0, 0),
('Gloss Black', '100ML', 'direct', 'Enamel', 0, 0),
('Gloss Black', '200ML', 'direct', 'Enamel', 0, 0),
('Gloss Black', '500ML', 'direct', 'Enamel', 0, 0),
('Gloss Black', '1L', 'direct', 'Enamel', 0, 0),
('Gloss Black', '4L', 'direct', 'Enamel', 0, 0),
('Gloss Br White', '100ML', 'direct', 'Enamel', 0, 0),
('Gloss Br White', '4L', 'direct', 'Enamel', 0, 0),
('Gloss Brilliant White', '1L', 'direct', 'Enamel', 0, 0),
('Gloss Dark Brown', '100ML', 'direct', 'Enamel', 0, 0),
('Gloss Dark Brown', '500ML', 'direct', 'Enamel', 0, 0),
('Gloss Golden Brown', '200ML', 'direct', 'Enamel', 0, 0),
('Gloss Golden Brown', '1L', 'direct', 'Enamel', 0, 0),
('Gloss Golden Brown', '20L', 'direct', 'Enamel', 0, 0),
('Gloss Golden Yellow', '100ML', 'direct', 'Enamel', 0, 0),
('Gloss Intermediate Base', '500ML', 'base', 'Enamel', 0, 0),
('Gloss Intermediate Base New', '900ML', 'base', 'Enamel', 0, 0),
('Gloss Leaf Brown', '500ML', 'direct', 'Enamel', 0, 0),
('Gloss Leaf Brown', '1L', 'direct', 'Enamel', 0, 0),
('Gloss Mahogany', '500ML', 'direct', 'Enamel', 0, 0),
('Gloss Middle Buff', '500ML', 'direct', 'Enamel', 0, 0),
('Gloss Mim Green', '100ML', 'direct', 'Enamel', 0, 0),
('Gloss Off White', '500ML', 'direct', 'Enamel', 0, 0),
('Gloss Oxford Blue', '200ML', 'direct', 'Enamel', 0, 0),
('Gloss Oxford Blue', '4L', 'direct', 'Enamel', 0, 0),
('Gloss Phiroza', '100ML', 'direct', 'Enamel', 0, 0),
('Gloss Phiroza', '500ML', 'direct', 'Enamel', 0, 0),
('Gloss Phiroza Blue', '4L', 'direct', 'Enamel', 0, 0),
('Gloss Po Red', '100ML', 'direct', 'Enamel', 0, 0),
('Gloss Po Red', '200ML', 'direct', 'Enamel', 0, 0),
('Gloss Po Red', '500ML', 'direct', 'Enamel', 0, 0),
('Gloss Po Red', '4L', 'direct', 'Enamel', 0, 0),
('Gloss Signal Red', '1L', 'direct', 'Enamel', 0, 0),
('Gloss Smoke Grey', '200ML', 'direct', 'Enamel', 0, 0),
('Gloss Smoke Grey', '1L', 'direct', 'Enamel', 0, 0),
('Gloss White Base', '500ML', 'base', 'Enamel', 0, 0),
('Gloss White Base', '1L', 'base', 'Enamel', 0, 0),
('Gloss White Base New', '4L', 'base', 'Enamel', 0, 0),
('Green Thread', '9 Inch', 'direct', 'Hardware', 0, 0),
('Grg Beading Corner', 'Standard', 'direct', 'Hardware', 0, 0),
('Grg Centar Panel', '7 Inch', 'direct', 'Hardware', 0, 0),
('Grg Centar Panel', '8 Inch', 'direct', 'Hardware', 0, 0),
('Grg Cornice Corner', 'Standard', 'direct', 'Hardware', 0, 0),
('Grw Tinter Green', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Gurmala', 'Standard', 'direct', 'Tools/Brushes', 0, 0),
('Gypsum Board', 'Standard', 'direct', 'Hardware', 0, 0),
('Gypsum Plaster Board 1830x1220', '12mm', 'direct', 'Hardware', 0, 0),
('Gypsum Plaster Board 6x4', '12mm', 'direct', 'Hardware', 0, 0),
('Halo Mist Ext Silk He1', '1L', 'direct', 'Emulsion', 0, 0),
('Halo Mist Ext Silk He2', '1L', 'direct', 'Emulsion', 0, 0),
('Halo Mist Ext Silk He2', '4L', 'direct', 'Emulsion', 0, 0),
('Halo Mist Ext Silk He3', '975ML', 'direct', 'Emulsion', 0, 0),
('Halo Mist Ext Silk He3', '9.75L', 'direct', 'Emulsion', 0, 0),
('Halo Mist Ext Silk He4', '950ML', 'direct', 'Emulsion', 0, 0),
('Halo Mist Ext Silk He4', '3.8L', 'direct', 'Emulsion', 0, 0),
('Halo Mist Ext Silk He4', '9.5L', 'direct', 'Emulsion', 0, 0),
('Hc Gi Ceiling Inter', '12FT', 'direct', 'Hardware', 0, 0),
('Hc Gi Ceiling L Angle', '8FT', 'direct', 'Hardware', 0, 0),
('Hc Gi Ceiling Main Bottom', '8FT', 'direct', 'Hardware', 0, 0),
('Hc Gi Ceiling Perimeter', '12FT', 'direct', 'Hardware', 0, 0),
('Hc Gi Ceiling Section', '12FT', 'direct', 'Hardware', 0, 0),
('Hi Performance Enamel Silver', '50ML', 'direct', 'Enamel', 0, 0),
('Hi Performance Enamel Silver', '100ML', 'direct', 'Enamel', 0, 0),
('Hi Performance Enamel Silver', '200ML', 'direct', 'Enamel', 0, 0),
('Hi Performance Enamel Titanium White', '500ML', 'direct', 'Enamel', 0, 0),
('Hi Performance Smoke Gray', '500ML', 'direct', 'Enamel', 0, 0),
('I Blok Waterstop Damploc Int', '1L', 'direct', 'Waterproofing', 0, 0),
('I Blok Waterstop Primecoat Ext Wht', '10L', 'direct', 'Waterproofing', 0, 0),
('I Blok Waterstop Primecoat Ext Wht', '20L', 'direct', 'Waterproofing', 0, 0),
('I Blok Waterstop Primecoat Int Wht', '10L', 'direct', 'Waterproofing', 0, 0),
('I Blok Waterstop Primecoat Int Wht', '20L', 'direct', 'Waterproofing', 0, 0),
('I Blok Waterstop Putty Cem Wht', '40KG', 'direct', 'Putty', 0, 0),
('I Blok Waterstop Putty Cem Wht Pch', '5KG', 'direct', 'Putty', 0, 0),
('Ishyn 1k Pu Clr', '500ML', 'direct', 'Enamel', 0, 0),
('Jk Plain Putty', 'Standard', 'direct', 'Putty', 0, 0),
('Jk Red Oxide Metal Primer', '500ML', 'direct', 'Primer', 0, 0),
('JN Acrylic Putty', '1KG', 'direct', 'Putty', 0, 0),
('JN Acrylic Putty', '20KG', 'direct', 'Putty', 0, 0),
('JN Enamel Thinner', '1L', 'direct', 'Thinner', 0, 0),
('Joie Cls Ext Matt Joe1', '1L', 'direct', 'Emulsion', 0, 0),
('Joie Cls Ext Matt Joe1', '4L', 'direct', 'Emulsion', 0, 0),
('Joie Cls Ext Matt Joe3', '10L', 'direct', 'Emulsion', 0, 0),
('Joie Cls Ext Matt Joe3', '20L', 'direct', 'Emulsion', 0, 0),
('Joie Cls Ext Matt Joe3', '4L', 'direct', 'Emulsion', 0, 0),
('Joie Cls Ext Matt Joey', '10L', 'direct', 'Emulsion', 0, 0),
('Joie Cls Int Matt Bwht', '0.65L', 'direct', 'Emulsion', 0, 0),
('Joie Cls Int Matt Jo1', '1L', 'direct', 'Emulsion', 0, 0),
('Joie Cls Int Matt Jo1', '4L', 'direct', 'Emulsion', 0, 0),
('Joie Cls Int Matt Jo1', '10L', 'direct', 'Emulsion', 0, 0),
('Joie Cls Int Matt Jo1', '20L', 'direct', 'Emulsion', 0, 0),
('Joie Cls Int Matt Jo3', '1L', 'direct', 'Emulsion', 0, 0),
('Joie Cls Int Matt Jo3', '4L', 'direct', 'Emulsion', 0, 0),
('Joie Cls Int Matt Jo3', '20L', 'direct', 'Emulsion', 0, 0),
('JSW Paints Eco Roller Int Rfek', '9 Inch', 'direct', 'Tools/Brushes', 0, 0),
('JSW Paints SB Primer Mtl Red Oxide', '1L', 'direct', 'Primer', 0, 0),
('JSW Paints SB Primer Mtl Red Oxide', '5L', 'direct', 'Primer', 0, 0),
('K Shield A Emulsion M.Red', '1L', 'direct', 'Emulsion', 0, 0),
('K Shield A Emulsion Slp Signal Red', '4L', 'direct', 'Emulsion', 0, 0),
('K Shield A Emulsion Terracotta', '50ML', 'direct', 'Emulsion', 0, 0),
('K Shield A Emulsion Terracotta', '1L', 'direct', 'Emulsion', 0, 0),
('K Shield A Emulsion Vibrant Orange', '500ML', 'direct', 'Emulsion', 0, 0),
('K Shield A Emulsion Vibrant Orange', '1L', 'direct', 'Emulsion', 0, 0),
('Kamo Shield Terracotta', '4L', 'direct', 'Emulsion', 0, 0),
('King Brush', '100mm', 'direct', 'Tools/Brushes', 0, 0),
('KP Red Oxide Metal Primer', '1L', 'direct', 'Primer', 0, 0),
('Krayons Wall Putty', '1KG', 'direct', 'Putty', 0, 0),
('Krayons Wall Putty', '5KG', 'direct', 'Putty', 0, 0),
('Krayons Wall Putty', '40KG', 'direct', 'Putty', 0, 0),
('Lamited Gypsum Ceiling Tiles', 'Standard', 'direct', 'Hardware', 0, 0),
('LFY Tinter Light Fast Yellow', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('LWCP', '20KG', 'direct', 'Putty', 0, 0),
('Mag Tinter Magenta', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Metallic Accent Gold', '100ML', 'direct', 'Enamel', 0, 0),
('Metallic Accent Gold', '200ML', 'direct', 'Enamel', 0, 0),
('Metallic Accent Gold', '500ML', 'direct', 'Enamel', 0, 0),
('Metallic Paint', '100ML', 'direct', 'Enamel', 0, 0),
('Metallic Paint', '200ML', 'direct', 'Enamel', 0, 0),
('Metallic Paint', '500ML', 'direct', 'Enamel', 0, 0),
('Metallic Paint', '1L', 'direct', 'Enamel', 0, 0),
('Mineral Oil', '1000ML', 'direct', 'Thinner', 0, 0),
('Mineral Oil', '2000ML', 'direct', 'Thinner', 0, 0),
('Mineral Oil', '4000ML', 'direct', 'Thinner', 0, 0),
('MRF Melamine Sealer Clear', '8L', 'direct', 'Primer', 0, 0),
('Natural Gypsum Calcined Plaster', '20KG', 'direct', 'Hardware', 0, 0),
('Natural Gypsum Calcined Plaster', '25KG', 'direct', 'Hardware', 0, 0),
('NC Brown', '1L', 'direct', 'Enamel', 0, 0),
('NC Maroon', '1L', 'direct', 'Enamel', 0, 0),
('NC Po Red', '1L', 'direct', 'Enamel', 0, 0),
('NC Thinner Premium Grade', '1L', 'direct', 'Thinner', 0, 0),
('Nerolac Brush', '1 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Nerolac Brush', '2 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Nerolac Roller', '4 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Nerolac Roller 452', '4 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Nerolac Roller Ext', '6 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Nerolac Roller Ext', '9 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Nerolac Waterproof Premium Putty', '40KG', 'direct', 'Putty', 0, 0),
('NS 97 Calista Neo Star', '4L', 'direct', 'Emulsion', 0, 0),
('NSS 1 Calista Neo Star Shine', '1L', 'direct', 'Emulsion', 0, 0),
('NSS 1 Calista Neo Star Shine', '4L', 'direct', 'Emulsion', 0, 0),
('NSS 1 Calista Neo Star Shine', '10L', 'direct', 'Emulsion', 0, 0),
('NSS 1 Calista Neo Star Shine', '20L', 'direct', 'Emulsion', 0, 0),
('NSS 2 Calista Neo Star Shine', '975ML', 'direct', 'Emulsion', 0, 0),
('NSS 2 Calista Neo Star Shine', '9.75L', 'direct', 'Emulsion', 0, 0),
('NSS 2 Calista Neo Star Shine', '19.5L', 'direct', 'Emulsion', 0, 0),
('NSS 2 Calista Neo Star Shine', '39L', 'direct', 'Emulsion', 0, 0),
('NSS 99 Calista Neo Star Shine', '975ML', 'direct', 'Emulsion', 0, 0),
('NSS 99 Calista Neo Star Shine', '3.5L', 'direct', 'Emulsion', 0, 0),
('NSS 99 Calista Neo Star Shine', '9.75L', 'direct', 'Emulsion', 0, 0),
('Oxri Tinter Red Oxide', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Painting Brush', '38mm', 'direct', 'Tools/Brushes', 0, 0),
('Painting Brush', '50mm', 'direct', 'Tools/Brushes', 0, 0),
('Painting Brush', '63mm', 'direct', 'Tools/Brushes', 0, 0),
('Painting Brush', '75mm', 'direct', 'Tools/Brushes', 0, 0),
('Painting Tray', 'Standard', 'direct', 'Tools/Brushes', 0, 0),
('Paint Brush 001 Sup', '25mm', 'direct', 'Tools/Brushes', 0, 0),
('Paint Brush 511tsup', '100mm', 'direct', 'Tools/Brushes', 0, 0),
('Paint Brush Ab Sup', '100mm', 'direct', 'Tools/Brushes', 0, 0),
('Paint Brush B-5 Sup', '100mm', 'direct', 'Tools/Brushes', 0, 0),
('Paint Brush Miton King', '100mm', 'direct', 'Tools/Brushes', 0, 0),
('Paint Remover', '1L', 'direct', 'Thinner', 0, 0),
('PB 2 Style Power Bright', '975ML', 'direct', 'Emulsion', 0, 0),
('PB 2 Style Power Bright', '3.9L', 'direct', 'Emulsion', 0, 0),
('PB 2 Style Power Bright', '9.75L', 'direct', 'Emulsion', 0, 0),
('PB1 Style Power Bright', '1L', 'direct', 'Emulsion', 0, 0),
('PB1 Style Power Bright', '4L', 'direct', 'Emulsion', 0, 0),
('PB1 Style Power Bright', '10L', 'direct', 'Emulsion', 0, 0),
('PB1 Style Power Bright', '20L', 'direct', 'Emulsion', 0, 0),
('PB White Style Power Bright', '20L', 'direct', 'Emulsion', 0, 0),
('PCP WH Calista Perfect Choice Primer', '10L', 'direct', 'Primer', 0, 0),
('PCP WH Calista Perfect Choice Primer', '20L', 'direct', 'Primer', 0, 0),
('PF 13 Style Power Fit', '1L', 'direct', 'Emulsion', 0, 0),
('PF 13 Style Power Fit', '4L', 'direct', 'Emulsion', 0, 0),
('PF 13 Style Power Fit', '20L', 'direct', 'Emulsion', 0, 0),
('PF 96 Style Power Fit', '1L', 'direct', 'Emulsion', 0, 0),
('PF 96 Style Power Fit', '4L', 'direct', 'Emulsion', 0, 0),
('PFP WH Style Pro Fresh Primer', '1L', 'direct', 'Primer', 0, 0),
('PFP WH Style Pro Fresh Primer', '4L', 'direct', 'Primer', 0, 0),
('PFP WH Style Pro Fresh Primer', '10L', 'direct', 'Primer', 0, 0),
('PFP WH Style Pro Fresh Primer', '20L', 'direct', 'Primer', 0, 0),
('PHP White Style Pro Hide Primer', '1L', 'direct', 'Primer', 0, 0),
('PHP White Style Pro Hide Primer', '4L', 'direct', 'Primer', 0, 0),
('PHP White Style Pro Hide Primer', '10L', 'direct', 'Primer', 0, 0),
('PHP White Style Pro Hide Primer', '20L', 'direct', 'Primer', 0, 0),
('Pixa Elg Ext Matt PE1', '1L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Matt PE1', '4L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Matt PE1', '10L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Matt PE1', '20L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Matt PE2', '1L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Matt PE2', '4L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Matt PE2', '10L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Matt PE2', '20L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Matt PE3', '975ML', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Matt PE3', '9.75L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Matt PE3', '19.5L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Matt PE4', '950ML', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Matt PE4', '3.8L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Matt PE4', '9.5L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Matt PE4', '19L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Matt PEY', '975ML', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Matt PEY', '3.8L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Matt PEY', '9.75L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Silk PSE1', '1L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Silk PSE1', '4L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Silk PSE1', '10L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Silk PSE1', '20L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Silk PSE2', '1L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Silk PSE2', '4L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Silk PSE2', '10L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Silk PSE2', '20L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Silk PSE3', '975ML', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Silk PSE3', '9.75L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Silk PSE3', '19.5L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Silk PSE4', '9.5L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Ext Silk PSE4', '19L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Matt PI1', '1L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Matt PI1', '4L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Matt PI1', '10L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Matt PI1', '20L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Matt PI3', '975ML', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Matt PI3', '3.9L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Matt PI3', '9.75L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Matt PI3', '19.5L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Matt PI4', '950ML', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Matt PI4', '3.8L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Matt PI4', '9.5L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Matt PI4', '19L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Silk PSI1', '1L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Silk PSI1', '4L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Silk PSI1', '10L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Silk PSI3', '975ML', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Silk PSI3', '3.9L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Silk PSI3', '9.75L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Silk PSI3', '19.5L', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Silk PSI4', '950ML', 'direct', 'Emulsion', 0, 0),
('Pixa Elg Int Silk PSI4', '3.8L', 'direct', 'Emulsion', 0, 0),
('Plain Putty', '40KG', 'direct', 'Putty', 0, 0),
('PPP White One Pro Primer And Putty', '10KG', 'direct', 'Primer', 0, 0),
('PPP White One Pro Primer And Putty', '20KG', 'direct', 'Primer', 0, 0),
('Promise 2 IN1 Primer Int Ext', '10L', 'direct', 'Primer', 0, 0),
('Promise 2 IN1 Primer Int Ext', '20L', 'direct', 'Primer', 0, 0),
('Promise Accent Base', '3.6L', 'base', 'Emulsion', 0, 0),
('Promise BR White', '4L', 'direct', 'Emulsion', 0, 0),
('Promise Enml Black', '20L', 'direct', 'Enamel', 0, 0),
('Promise Exterior 92 Base', '20L', 'base', 'Emulsion', 0, 0),
('Promise Exterior 94 Base', '4L', 'base', 'Emulsion', 0, 0),
('Promise Exterior 98 Base', '4L', 'base', 'Emulsion', 0, 0),
('Promise Exterior Br White Base', '20L', 'base', 'Emulsion', 0, 0),
('Promise Exterior White Base', '1L', 'base', 'Emulsion', 0, 0),
('Promise Exterior White Base', '4L', 'base', 'Emulsion', 0, 0),
('Promise Exterior White Base', '20L', 'base', 'Emulsion', 0, 0),
('Promise Interior 92 Base', '1L', 'base', 'Emulsion', 0, 0),
('Promise Interior 92 Base', '10L', 'base', 'Emulsion', 0, 0),
('Promise Interior 92 Base', '20L', 'base', 'Emulsion', 0, 0),
('Promise Interior 94 Base', '1L', 'base', 'Emulsion', 0, 0),
('Promise Interior 96 Base', '4L', 'base', 'Emulsion', 0, 0),
('Promise Interior ST Base', '4L', 'base', 'Emulsion', 0, 0),
('Promise Interior Accent Base', '3.6L', 'base', 'Emulsion', 0, 0),
('Promise Interior Intermediate Base', '900ML', 'base', 'Emulsion', 0, 0),
('Promise Interior Intermediate Base', '3.6L', 'base', 'Emulsion', 0, 0),
('Promise Interior Red Base', '900ML', 'base', 'Emulsion', 0, 0),
('Promise Interior White Base', '1L', 'base', 'Emulsion', 0, 0),
('Promise Interior White Base', '4L', 'base', 'Emulsion', 0, 0),
('Promise Interior White Base', '10L', 'base', 'Emulsion', 0, 0),
('Promise Interior White Base', '20L', 'base', 'Emulsion', 0, 0),
('Promise Interior Yellow Base', '900ML', 'base', 'Emulsion', 0, 0),
('Promise Intermediate Base', '3.6L', 'base', 'Emulsion', 0, 0),
('Promise Primer', '1L', 'direct', 'Primer', 0, 0),
('Promise Primer', '10L', 'direct', 'Primer', 0, 0),
('Promise Primer', '20L', 'direct', 'Primer', 0, 0),
('Promise Sheen Exterior 94 Base', '1L', 'base', 'Emulsion', 0, 0),
('Promise Sheen Exterior 94 Base', '4L', 'base', 'Emulsion', 0, 0),
('Promise Sheen Exterior Br White', '4L', 'direct', 'Emulsion', 0, 0),
('Promise Sheen Exterior White Base', '1L', 'base', 'Emulsion', 0, 0),
('Promise Sheen Exterior White Base', '4L', 'base', 'Emulsion', 0, 0),
('Promise Sheen Exterior White Base', '10L', 'base', 'Emulsion', 0, 0),
('Promise Sheen Interior 92 Base', '10L', 'base', 'Emulsion', 0, 0),
('Promise Sheen Interior 94 Base', '1L', 'base', 'Emulsion', 0, 0),
('Promise Sheen Interior Metal Base', '1L', 'base', 'Emulsion', 0, 0),
('Promise Sheen Interior White Base', '1L', 'base', 'Emulsion', 0, 0),
('Promise Sheen Interior White Base', '4L', 'base', 'Emulsion', 0, 0),
('Promise Sheen Interior White Base', '10L', 'base', 'Emulsion', 0, 0),
('Promise Sheen Interior White Base', '20L', 'base', 'Emulsion', 0, 0),
('Promise Smart C. Acrylic Distemper', '20KG', 'direct', 'Emulsion', 0, 0),
('Promise Smart Ch Ext Br White Base', '4L', 'base', 'Emulsion', 0, 0),
('Promise Smart Ch Ext Br White Base', '20L', 'base', 'Emulsion', 0, 0),
('Promise Smart Ch Ext Primer', '4L', 'direct', 'Primer', 0, 0),
('Promise Smart Ch Ext Primer', '10L', 'direct', 'Primer', 0, 0),
('Promise Smart Ch Ext Primer', '20L', 'direct', 'Primer', 0, 0),
('Promise Smart Ch Int Br White Base', '4L', 'base', 'Emulsion', 0, 0),
('Promise Smart Ch Int Br White Base', '10L', 'base', 'Emulsion', 0, 0),
('Promise Smart Ch Int Br White Base', '20L', 'base', 'Emulsion', 0, 0),
('Promise Smart Ch Int Primer', '1L', 'direct', 'Primer', 0, 0),
('Promise Smart Ch Int Primer', '4L', 'direct', 'Primer', 0, 0),
('Promise Smart Ch Int Primer', '10L', 'direct', 'Primer', 0, 0),
('Promise Smart Ch Int Primer', '20L', 'direct', 'Primer', 0, 0),
('Promise Smart Choice Ext Primer', '10L', 'direct', 'Primer', 0, 0),
('Promise Smart Choice Int Primer', '10L', 'direct', 'Primer', 0, 0),
('Promise Smart Choice Int Primer', '20L', 'direct', 'Primer', 0, 0),
('Promise Smart Int Br White Base', '1L', 'base', 'Emulsion', 0, 0),
('Promise White Base', '1L', 'base', 'Emulsion', 0, 0),
('Promise Yellow Base', '900ML', 'base', 'Emulsion', 0, 0),
('PSP WH Calista Perfect Choice Primer', '20L', 'direct', 'Primer', 0, 0),
('PSP White Style Perfect Start Primer', '1L', 'direct', 'Primer', 0, 0),
('PSP White Style Perfect Start Primer', '4L', 'direct', 'Primer', 0, 0),
('PSP White Style Perfect Start Primer', '10L', 'direct', 'Primer', 0, 0),
('PU Clear Sealer', '1L', 'direct', 'Enamel', 0, 0),
('PU Enamel Black', '500ML', 'direct', 'Enamel', 0, 0),
('PU Enamel Dark Brown', '1L', 'direct', 'Enamel', 0, 0),
('PU Enamel Silver Pant', '50ML', 'direct', 'Enamel', 0, 0),
('PU Enamel Silver Pant', '100ML', 'direct', 'Enamel', 0, 0),
('PU Enamel Smoke Grey', '1L', 'direct', 'Enamel', 0, 0),
('PU Enamel White', '1L', 'direct', 'Enamel', 0, 0),
('PU Semi Gloss', '1L', 'direct', 'Enamel', 0, 0),
('Putty Blade 3', '3 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Putty Blade 4', '4 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Putty Blade 6', '6 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Putty Blade Hard 6', '6 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Putty Blade Hard 8', '8 Inch', 'direct', 'Tools/Brushes', 0, 0),
('Putty Fine', '40KG', 'direct', 'Putty', 0, 0),
('Putty Ftl Cem Sindl Wd Tkn Frag', '20KG', 'direct', 'Putty', 0, 0),
('Putty Ftl Cem Sindl Wd Tkn Frag', '40KG', 'direct', 'Putty', 0, 0),
('PVC Sleeve', 'Standard', 'direct', 'Hardware', 0, 0),
('Rangoli Brush 5', 'Standard', 'direct', 'Tools/Brushes', 0, 0),
('Red Oxide Metal Primer', '500ML', 'direct', 'Primer', 0, 0),
('Red Oxide Primer Solvent Thinnable', '200ML', 'direct', 'Primer', 0, 0),
('Red Oxide Primer Solvent Thinnable', '500ML', 'direct', 'Primer', 0, 0),
('Red Stone Sup Painting Brush', '100mm', 'direct', 'Tools/Brushes', 0, 0),
('Roller 46', 'Standard', 'direct', 'Tools/Brushes', 0, 0),
('Roller Brush', 'Standard', 'direct', 'Tools/Brushes', 0, 0),
('Roller Brush 6', '6 Inch', 'direct', 'Tools/Brushes', 0, 0),
('ROM Primer', '500ML', 'direct', 'Primer', 0, 0),
('ROM Primer', '1L', 'direct', 'Primer', 0, 0),
('ROM Primer', '4L', 'direct', 'Primer', 0, 0),
('Rovere Lite', '20L', 'direct', 'Emulsion', 0, 0),
('Sadolin 2k PU Thinner', '1L', 'direct', 'Thinner', 0, 0),
('Sadolin Ce 1k PU Gloss', '1L', 'direct', 'Enamel', 0, 0),
('Sadolin Int Clr 1k PU Gloss', '500ML', 'direct', 'Enamel', 0, 0),
('Sadolin Int Clr 1k PU Gloss', '4L', 'direct', 'Enamel', 0, 0),
('Sadolin Int Clr 2k PU Gloss', '1L', 'direct', 'Enamel', 0, 0),
('Sadolin Int Clr Melamine Gloss', '1L', 'direct', 'Enamel', 0, 0),
('Sadolin Interior 2k PU Sealer', '1L', 'direct', 'Enamel', 0, 0),
('Sadolin Melamine Thinner', '1L', 'direct', 'Thinner', 0, 0),
('Sadolin NC Clear Lacquer', '1L', 'direct', 'Enamel', 0, 0),
('Sadolin NC Sanding Sealer', '500ML', 'direct', 'Enamel', 0, 0),
('Sadolin NC Sanding Sealer', '1L', 'direct', 'Enamel', 0, 0),
('Sadolin NC Wood Thinner', '1L', 'direct', 'Thinner', 0, 0),
('Sadolin NC Wood Thinner', '4L', 'direct', 'Thinner', 0, 0),
('Sadolin Wood Filler White', '1KG', 'direct', 'Putty', 0, 0),
('Sat Fin Accent Base', '900ML', 'base', 'Emulsion', 0, 0),
('Sat Fin Accent Base', '0.9L', 'base', 'Emulsion', 0, 0),
('Sat Fin White', '4L', 'direct', 'Emulsion', 0, 0),
('Sat Fin White Base New', '1L', 'base', 'Emulsion', 0, 0),
('Satin Accent Base', '3.6L', 'base', 'Emulsion', 0, 0),
('SB Cement Primer', '1L', 'direct', 'Primer', 0, 0),
('Screw 19mm', '19mm', 'direct', 'Hardware', 0, 0),
('Screw 25mm', '25mm', 'direct', 'Hardware', 0, 0),
('SGE Ad Grey Calista Sparkle Gloss', '1L', 'direct', 'Enamel', 0, 0),
('SGE Black Calista Sparkle Gloss', '100ML', 'direct', 'Enamel', 0, 0),
('SGE Black Calista Sparkle Gloss', '200ML', 'direct', 'Enamel', 0, 0),
('SGE Black Calista Sparkle Gloss', '500ML', 'direct', 'Enamel', 0, 0),
('SGE Black Calista Sparkle Gloss', '1L', 'direct', 'Enamel', 0, 0),
('SGE Black Calista Sparkle Gloss', '4L', 'direct', 'Enamel', 0, 0),
('SGE Brown Calista Sparkle Gloss', '100ML', 'direct', 'Enamel', 0, 0),
('SGE Brown Calista Sparkle Gloss', '200ML', 'direct', 'Enamel', 0, 0),
('SGE Brown Calista Sparkle Gloss', '500ML', 'direct', 'Enamel', 0, 0),
('SGE Brown Calista Sparkle Gloss', '1L', 'direct', 'Enamel', 0, 0),
('SGE Brown Calista Sparkle Gloss', '4L', 'direct', 'Enamel', 0, 0),
('SGE Br White Calista Sparkle Gloss', '200ML', 'direct', 'Enamel', 0, 0),
('SGE Br White Calista Sparkle Gloss', '500ML', 'direct', 'Enamel', 0, 0),
('SGE Br White Calista Sparkle Gloss', '1L', 'direct', 'Enamel', 0, 0),
('SGE Br White Calista Sparkle Gloss', '4L', 'direct', 'Enamel', 0, 0),
('SGE Gl Brown Calista Sparkle Gloss', '500ML', 'direct', 'Enamel', 0, 0),
('SGE Gl Brown Calista Sparkle Gloss', '1L', 'direct', 'Enamel', 0, 0),
('SGE Gl Brown Calista Sparkle Gloss', '4L', 'direct', 'Enamel', 0, 0),
('SGE Gold Calista Sparkle Gloss', '1L', 'direct', 'Enamel', 0, 0),
('SGE S Grey Calista Sparkle Gloss', '20L', 'direct', 'Enamel', 0, 0),
('SGE Sky Blue Calista Sparkle Gloss', '4L', 'direct', 'Enamel', 0, 0),
('SGE Wl Lilac Calista Sparkle Gloss', '500ML', 'direct', 'Enamel', 0, 0),
('SGE Wl Lilac Calista Sparkle Gloss', '1L', 'direct', 'Enamel', 0, 0),
('Shiro Thinner Pl', '20L', 'direct', 'Thinner', 0, 0),
('Shino Thinner PTL', '5L', 'direct', 'Thinner', 0, 0),
('Sirca NC Dark Brown', '1L', 'direct', 'Enamel', 0, 0),
('Sirca NC Golden Yellow', '1L', 'direct', 'Enamel', 0, 0),
('Sirca NC White', '1L', 'direct', 'Enamel', 0, 0),
('SNT 22 Allwood Excel One Thinner', '1L', 'direct', 'Thinner', 0, 0),
('SNT 22 Allwood Excel One Thinner', '5L', 'direct', 'Thinner', 0, 0),
('Special 2.5', 'Standard', 'direct', 'Hardware', 0, 0),
('Special 5.3', 'Standard', 'direct', 'Hardware', 0, 0),
('Special', '10-1-15-15', 'direct', 'Hardware', 0, 0),
('SPNT 22 Allwood Excel 1 Smith Thinner', '1L', 'direct', 'Thinner', 0, 0),
('SPNT 22 Allwood Excel 1 Smith Thinner', '5L', 'direct', 'Thinner', 0, 0),
('Spray Paint Silver', '400ML', 'direct', 'Enamel', 0, 0),
('SRP ROXD Calista Sparkle RO Primer', '1L', 'direct', 'Primer', 0, 0),
('SRP ROXD Calista Sparkle RO Primer', '4L', 'direct', 'Primer', 0, 0),
('SR Spray Paint Black', '400ML', 'direct', 'Enamel', 0, 0),
('SR Spray Paint Deep Orange', '400ML', 'direct', 'Enamel', 0, 0),
('SR Spray Paint Gold', '400ML', 'direct', 'Enamel', 0, 0),
('SR Spray Paint Silver', '400ML', 'direct', 'Enamel', 0, 0),
('Stainer Black', '200ML', 'direct', 'Tinter/Colorant', 0, 0),
('Stainer Diluted Pack', '100ML', 'direct', 'Tinter/Colorant', 0, 0),
('Stainer Fast Blue', '50ML', 'direct', 'Tinter/Colorant', 0, 0),
('Stainer Fast Yellow Green', '50ML', 'direct', 'Tinter/Colorant', 0, 0),
('Stainer Fast Yellow Green', '100ML', 'direct', 'Tinter/Colorant', 0, 0),
('Stainer Fast Yellow Green', '200ML', 'direct', 'Tinter/Colorant', 0, 0),
('Stainer Yellow Oxide', '100ML', 'direct', 'Tinter/Colorant', 0, 0),
('Stencil Fairy', 'Standard', 'direct', 'Hardware', 0, 0),
('Stencil Green Key', 'Standard', 'direct', 'Hardware', 0, 0),
('Stencil 16-24', 'Standard', 'direct', 'Hardware', 0, 0),
('Style Stainer Black', '200ML', 'direct', 'Tinter/Colorant', 0, 0),
('Style Stainer Fast Red', '200ML', 'direct', 'Tinter/Colorant', 0, 0),
('Style Stainer Fast Violet', '50ML', 'direct', 'Tinter/Colorant', 0, 0),
('Style Stainer Fast Violet', '100ML', 'direct', 'Tinter/Colorant', 0, 0),
('Style Stainer Fast Violet', '200ML', 'direct', 'Tinter/Colorant', 0, 0),
('Style Stainer Fast Yello Green', '20ML', 'direct', 'Tinter/Colorant', 0, 0),
('Superclean Accent Base', '10L', 'base', 'Emulsion', 0, 0),
('Superclean Intermediate Base', '1L', 'base', 'Emulsion', 0, 0),
('Super Clean New 90 Base', '1L', 'base', 'Emulsion', 0, 0),
('Super Clean New 90 Base', '4L', 'base', 'Emulsion', 0, 0),
('Super Clean New 90 Base', '10L', 'base', 'Emulsion', 0, 0),
('Super Clean New 90 Base', '20L', 'base', 'Emulsion', 0, 0),
('Super Clean New 92 Base', '1L', 'base', 'Emulsion', 0, 0),
('Super Clean Yellow 96 Base', '1L', 'base', 'Emulsion', 0, 0),
('SWP Pink Calista Sparkle Wood Primer', '1L', 'direct', 'Primer', 0, 0),
('SWP Pink Calista Sparkle Wood Primer', '4L', 'direct', 'Primer', 0, 0),
('SWP Wht Calista Sparkle Wood Primer', '1L', 'direct', 'Primer', 0, 0),
('SWP Wht Calista Sparkle Wood Primer', '4L', 'direct', 'Primer', 0, 0),
('Terminator Wood', '250ML', 'direct', 'Other', 0, 0),
('Thinner GP Super', '200ML', 'direct', 'Thinner', 0, 0),
('Thinner GP Super', '400ML', 'direct', 'Thinner', 0, 0),
('Thinner GP Super', '4L', 'direct', 'Thinner', 0, 0),
('Thinner GP Super', '5L', 'direct', 'Thinner', 0, 0),
('Thinner GP Super', '900ML', 'direct', 'Thinner', 0, 0),
('Thinner J-9', '400ML', 'direct', 'Thinner', 0, 0),
('Thinner J-9', '600ML', 'direct', 'Thinner', 0, 0),
('Thinner J-9', '700ML', 'direct', 'Thinner', 0, 0),
('Thinner J-9', '800ML', 'direct', 'Thinner', 0, 0),
('Thinner J-9', '900ML', 'direct', 'Thinner', 0, 0),
('Thinner PTL', '1L', 'direct', 'Thinner', 0, 0),
('Thinner Super GP CG', '18L', 'direct', 'Thinner', 0, 0),
('Thinner Super GP CG', '21L', 'direct', 'Thinner', 0, 0),
('Thinnner Super GP CG', '210L', 'direct', 'Thinner', 0, 0),
('TLI 1 One True Life', '1L', 'direct', 'Emulsion', 0, 0),
('TLI 1 One True Life', '4L', 'direct', 'Emulsion', 0, 0),
('TLI 1 One True Life', '20L', 'direct', 'Emulsion', 0, 0),
('TLI 2 One True Life', '975ML', 'direct', 'Emulsion', 0, 0),
('TLI 2 One True Life', '9.75L', 'direct', 'Emulsion', 0, 0),
('TLI 2 One True Life', '19.5L', 'direct', 'Emulsion', 0, 0),
('TLI 2 One True Life', '39L', 'direct', 'Emulsion', 0, 0),
('Tray 225', 'Standard', 'direct', 'Tools/Brushes', 0, 0),
('UL Gi Ceiling Inter', '12FT', 'direct', 'Hardware', 0, 0),
('UL Gi Ceiling L Angel', '8FT', 'direct', 'Hardware', 0, 0),
('UL Gi Ceiling L Angel', '12FT', 'direct', 'Hardware', 0, 0),
('UL Gi Ceiling Main Bottom', '8FT', 'direct', 'Hardware', 0, 0),
('UL Gi Ceiling Perimeter', '12FT', 'direct', 'Hardware', 0, 0),
('UL Gi Ceiling Section', '12FT', 'direct', 'Hardware', 0, 0),
('Ultra Nitro Sealer', '1L', 'direct', 'Primer', 0, 0),
('Ultra Nitro Sealer', '4L', 'direct', 'Primer', 0, 0),
('Ultracel Ceiling Drywall Tape', 'Standard', 'direct', 'Hardware', 0, 0),
('Ultracel Wire Mesh Roll', 'Standard', 'direct', 'Hardware', 0, 0),
('Universal Stainer Black', '50ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Black', '100ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Black', '200ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Fast Blue', '50ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Fast Blue', '100ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Fast Blue', '200ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Fast Green', '50ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Fast Green', '100ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Fast Green', '200ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Fast Orange', '50ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Fast Orange', '100ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Fast Orange', '200ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Fast Red', '200ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Fast Red', '500ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Fast Violet', '50ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Fast Violet', '100ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Fast Violet', '200ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Fast Yellow', '50ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Fast Yellow', '100ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Fast Yellow', '200ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Yellow Oxide', '50ML', 'direct', 'Tinter/Colorant', 0, 0),
('Universal Stainer Yellow Oxide', '200ML', 'direct', 'Tinter/Colorant', 0, 0),
('VAF Metallic Silver', '1L', 'direct', 'Enamel', 0, 0),
('VT Diamond 90 Base', '1L', 'base', 'Emulsion', 0, 0),
('VT Diamond 90 Base', '4L', 'base', 'Emulsion', 0, 0),
('VT Diamond 90 Base', '10L', 'base', 'Emulsion', 0, 0),
('VT Diamond 90 Base', '11L', 'base', 'Emulsion', 0, 0),
('VT Diamond 90 Base', '20L', 'base', 'Emulsion', 0, 0),
('VT Diamond 92 Base', '1L', 'base', 'Emulsion', 0, 0),
('VT Diamond 92 Base', '20L', 'base', 'Emulsion', 0, 0),
('VT Diamond White Base', '1L', 'base', 'Emulsion', 0, 0),
('VT Diamond White Base', '4L', 'base', 'Emulsion', 0, 0),
('VT Eterna 90 Base', '1L', 'base', 'Emulsion', 0, 0),
('VT Eterna 90 Base', '20L', 'base', 'Emulsion', 0, 0),
('VT Pearl Glo Accent Base', '900ML', 'base', 'Emulsion', 0, 0),
('VT Pearl Glo New White Base', '1L', 'base', 'Emulsion', 0, 0),
('VT Pearl Glo New White Base', '10L', 'base', 'Emulsion', 0, 0),
('Wall Paints Stencils', 'Standard', 'direct', 'Hardware', 0, 0),
('Wall Prim Joie Ext Wht', '10L', 'direct', 'Primer', 0, 0),
('Wall Prim Joie Ext Wht', '20L', 'direct', 'Primer', 0, 0),
('Wall Prim Joie Int Wht', '10L', 'direct', 'Primer', 0, 0),
('Wall Prim Joie Int Wht', '20L', 'direct', 'Primer', 0, 0),
('Wall Putty Acrylic Wht', '5KG', 'direct', 'Putty', 0, 0),
('Wall Putty Cem Sndl Wd Fragrance', '40KG', 'direct', 'Putty', 0, 0),
('Wallstencil Srl Painting Tool', 'Standard', 'direct', 'Tools/Brushes', 0, 0),
('Washer', 'Standard', 'direct', 'Hardware', 0, 0),
('Waterproof Putty', '20KG', 'direct', 'Putty', 0, 0),
('WF4 White Alldry Wallfix 4', '4L', 'direct', 'Waterproofing', 0, 0),
('WF4 White Alldry Wallfix 4', '10L', 'direct', 'Waterproofing', 0, 0),
('WF4 White Alldry Wallfix 4', '20L', 'direct', 'Waterproofing', 0, 0),
('White Gi Short Cross T', '600MM', 'direct', 'Hardware', 0, 0),
('White Primer Solvent Thinnable', '500ML', 'direct', 'Primer', 0, 0),
('WS 201 ABP', 'Standard', 'direct', 'Other', 0, 0),
('WS Alkali Bloc Primer', '4L', 'direct', 'Primer', 0, 0),
('WS Flash Accent Base', '900ML', 'base', 'Emulsion', 0, 0),
('WS Flash Accent Base', '3.6L', 'base', 'Emulsion', 0, 0),
('WS Flash Intermediate Base', '3.6L', 'base', 'Emulsion', 0, 0),
('WS Max 10YR 90 Base', '4L', 'base', 'Emulsion', 0, 0),
('WS Max 10YR 90 Base', '10L', 'base', 'Emulsion', 0, 0),
('WS Max 10YR 90 Base', '20L', 'base', 'Emulsion', 0, 0),
('WS Max 10YR 92 Base', '10L', 'base', 'Emulsion', 0, 0),
('WS Max 10YR 92 Base', '18L', 'base', 'Emulsion', 0, 0),
('WS Max 10YR 93 Base', '1L', 'base', 'Emulsion', 0, 0),
('WS Max Accent Base', '3.8L', 'base', 'Emulsion', 0, 0),
('WS Max Deep Base', '900ML', 'base', 'Emulsion', 0, 0),
('WS Max White Base', '1L', 'base', 'Emulsion', 0, 0),
('WS PF 15YR 90 Base', '10L', 'base', 'Emulsion', 0, 0),
('WS PF 15YR 90 Base', '20L', 'base', 'Emulsion', 0, 0),
('WS PF 15YR 92 Base', '4L', 'base', 'Emulsion', 0, 0),
('WS PF 15YR 92 Base', '18L', 'base', 'Emulsion', 0, 0),
('WS PF 15YR 93 Base', '1L', 'base', 'Emulsion', 0, 0),
('WS PF 92 Base', '18L', 'base', 'Emulsion', 0, 0),
('WS PF BR White', '1L', 'direct', 'Emulsion', 0, 0),
('WS PF Deep Base', '900ML', 'base', 'Emulsion', 0, 0),
('WS Power Flex 92 Base', '1L', 'base', 'Emulsion', 0, 0),
('WS Power Flex White Base', '4L', 'base', 'Emulsion', 0, 0),
('WS Powerflexx 93 Base', '3.7L', 'base', 'Emulsion', 0, 0),
('WS Protect Br White', '1L', 'direct', 'Emulsion', 0, 0),
('WS Protect Deep Base', '900ML', 'base', 'Emulsion', 0, 0),
('WS Protect Deep Base', '18L', 'base', 'Emulsion', 0, 0),
('WS Protect Dust Hi Sheen 90', '1L', 'direct', 'Emulsion', 0, 0),
('WS Protect Dust Hi Sheen 90', '4L', 'direct', 'Emulsion', 0, 0),
('WS Protect Dust Hi Sheen 90', '10L', 'direct', 'Emulsion', 0, 0),
('WS Protect Dust Hi Sheen 90', '20L', 'direct', 'Emulsion', 0, 0),
('WS Protect Dust Hi Sheen 90 Base', '4L', 'base', 'Emulsion', 0, 0),
('WS Protect Dust Hi Sheen 92', '1L', 'direct', 'Emulsion', 0, 0),
('WS Protect Dust Hi Sheen 93', '1L', 'direct', 'Emulsion', 0, 0),
('WS Protect Dustproof 90 Base', '1L', 'base', 'Emulsion', 0, 0),
('WS Protect Dustproof 90 Base', '10L', 'base', 'Emulsion', 0, 0),
('WS Protect Dustproof 92 Base', '1L', 'base', 'Emulsion', 0, 0),
('WS Protect Dustproof 98 Base', '1L', 'base', 'Emulsion', 0, 0),
('WS Protect Electric Blue', '1L', 'direct', 'Emulsion', 0, 0),
('WS Protect Electric Blue', '4L', 'direct', 'Emulsion', 0, 0),
('WS Protect Rainproof Accent Base', '900ML', 'base', 'Emulsion', 0, 0),
('WS Protect Rainproof White Base', '1L', 'base', 'Emulsion', 0, 0),
('WS Protect Red Base', '900ML', 'base', 'Emulsion', 0, 0),
('WS Protect Red Base', '3.6L', 'base', 'Emulsion', 0, 0),
('WS Protect Signal Red', '1L', 'direct', 'Emulsion', 0, 0),
('WS Protect Sunrise', '1L', 'direct', 'Emulsion', 0, 0),
('WS Protect Teracotta', '1L', 'direct', 'Emulsion', 0, 0),
('WS Protect Vibrant Yellow Base', '900ML', 'base', 'Emulsion', 0, 0),
('WS Protect White Base', '1L', 'base', 'Emulsion', 0, 0),
('WS Protect Yellow Base', '900ML', 'base', 'Emulsion', 0, 0),
('WS Teak 295', 'Standard', 'direct', 'Emulsion', 0, 0),
('WS Walnut', 'Standard', 'direct', 'Emulsion', 0, 0),
('WS Walnut 307', 'Standard', 'direct', 'Emulsion', 0, 0),
('WS Walnut 323', 'Standard', 'direct', 'Emulsion', 0, 0),
('WS Walnut 353', 'Standard', 'direct', 'Emulsion', 0, 0),
('WTP Aquatech Roof Coat', '20L', 'direct', 'Waterproofing', 0, 0),
('Xtra Touch Terracota', '1L', 'direct', 'Emulsion', 0, 0),
('Yox Tinter Yellow Oxide', '1L', 'direct', 'Tinter/Colorant', 0, 0),
('Zet Super', '25mm', 'direct', 'Hardware', 0, 0),
('Zet Super', '75mm', 'direct', 'Hardware', 0, 0),
('Zinc Yellow Metal Primer', '1L', 'direct', 'Primer', 0, 0),
('Zinc Yellow Metal Primer', '4L', 'direct', 'Primer', 0, 0);